
export const contacts = [
    {
        id: "1",
        name: "Alice Smith",
        email: "alice@example.com",
        phone: "+1 (555) 123-4567",
        tags: ["VIP", "Support"],
        lastSeen: "2 hours ago",
        status: "active",
    },
    {
        id: "2",
        name: "Bob Jones",
        email: "bob@example.com",
        phone: "+1 (555) 987-6543",
        tags: ["Lead"],
        lastSeen: "1 day ago",
        status: "inactive",
    },
    {
        id: "3",
        name: "Charlie Brown",
        email: "charlie@example.com",
        phone: "+1 (555) 555-5555",
        tags: ["New"],
        lastSeen: "30 mins ago",
        status: "active",
    },
    {
        id: "4",
        name: "David Lee",
        email: "david@example.com",
        phone: "+1 (555) 111-2222",
        tags: ["Support"],
        lastSeen: "5 mins ago",
        status: "active",
    },
    {
        id: "5",
        name: "Eva Green",
        email: "eva@example.com",
        phone: "+1 (555) 333-4444",
        tags: ["Lead", "Potential"],
        lastSeen: "3 days ago",
        status: "inactive",
    },
]
